project_name: httpie-to-curl
env:
  - GO111MODULE=on
builds:
  - main: ./cmd/httpie-to-curl
    binary: httpie-to-curl
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
